### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by nuest** [LibraryOfCongress/bagger#14]
I see a few changes to improve the README, I'd be happy to create a PR if you agree:

* use Markdown syntax for better readability on GitHub
* clarify which version of Java is required (the README mentions both `6` and `7`)
* add information where to find the created application after the gradle build to the running sections, i.e. point the reader to `/bagger/bagger/build/distributions` and to unzip the file `bagger.zip` and _then_ run the app (in case of Linux with `./bagger`, not `bagger.sh`). Or am I missing something?

**Comment by johnscancella** [comment]
Nuest, PR are great and always welcome.

For bullet point 2, I couldn't find the mention of java 6 and 7 in the README, but in either case it should be 7 which is already [EOL by Oracle](http://www.oracle.com/technetwork/java/eol-135779.html)

I have merged #15 which should fix the rest.

**Comment by nuest** [comment]
Great - thanks!

Re. the JAva 6 mentionen, I must have confused tabs with bagit-java.

Again, thanks for the quick fix.
