### ISSUE TITLE
Confusion: Where to download release?

### ISSUE THREAD

**Issue by pjotrek-b** [LibraryOfCongress/bagger#2]
At our archive, we are not only using Bagger/BagIt extensively, but also trying to promote its use for exchange with others (institution/individuals). Bagger is a great tool for making hashcode/fixity checks easily accessible for anyone. Thank you so very much!

**But:**
When trying to send "*a link*" to where to download Bagger to another institution, I realized that it's quite unclear, where to download the most recent LoC transfer-tools (bagger/bagit) - and which file actually...

I'm not complaining, but I think it'd be great to have a simple html-page that points to the most current releases - or did I simply not find it?

### Detailed information:
Here's a summary of things that add to the confusion:

* **Official download from Sourceforge or GitHub?**
On the [LoC Transfer-Tools Sourceforge site](http://sourceforge.net/projects/loc-xferutils/), it says that the project has moved to GitHub:
> As of 2013-07-12, this project may now be found at https://github.com/LibraryOfCongress/bagit-java

 ...where I can find the source-code, but no release packages.

* **The Sourceforge site seems to contain Bagger releases (currently up to v2.1.3):**
http://sourceforge.net/projects/loc-xferutils/files/loc-bagger/

 Now, not being sure if those releases are actually still maintained (or rather found on GitHub), there is a message that causes more insecurity if I'm right:
 
 > "Looking for the latest version? Download bagit-4.4-bin.zip (3.5 MB)"

 Which is actually the BagIt library/commandline application.

* **"loc-bil-java-library" = "bagit-java"**
Since the Bagger-releases on Sourceforge (still) work fine, I thought I'd check the date of the BagIt library/CLI releases on Sourceforge and compare them with the most recent changes on GitHub.

 Then I realized that:
  * on GitHub it's called "bagit-java", but on Sourceforge it's "loc-bil-java-library"
  * There seem to have been commits/releases on GitHub (v4.9.0), but not on SourceForge (v4.4)

 So now I'm even more insecure about the Bagger builds on Sourceforge... :(

Thank you very much in advance.

**Comment by dbrunton** [comment]
This is a confusing scenario. The current release for bagger is here:

https://github.com/LibraryOfCongress/bagger/releases/tag/v2.2

I'll update the README on the front page.

**Comment by dbrunton** [comment]
@pjotrek-b the bagit-java library also has releases on GitHub, here:

https://github.com/LibraryOfCongress/bagit-java/releases

Again, I think there may be some documentation that still points to the old location.

**Comment by pjotrek-b** [comment]
Thank you very much!
I must admit that I didn't know where to find the "releases" on GitHub... Shame on me ;)

About the updated README for Bagger:
Wouldn't it be better *not* to include a certain version number in the link, but rather point to 
https://github.com/LibraryOfCongress/bagger/releases/latest
or 
https://github.com/LibraryOfCongress/bagger/releases ?
