### ISSUE TITLE
Release Candidate bagger-2.5-RC2.zip prevents "Save-Bag-As" due to a bug

### ISSUE THREAD

**Issue by houzanme1** [LibraryOfCongress/bagger#21]
With bagger-2.5-RC2.zip, Create Bag in place works fine. 
Save Bag As does not work and generates the following error:
![save_bag_as_bug-2-16-16](https://cloud.githubusercontent.com/assets/879085/13088620/f59dbd60-d4ba-11e5-8caf-26a87815c8a9.JPG)

**Comment by johnscancella** [comment]
Can you attach the generated log files? They should be located in the same directory you installed bagger under /logs

**Comment by johnscancella** [comment]
should be fixed in version 2.5.0-RC3

**Comment by houzanme1** [comment]
Sounds good.

I attached the 2 log files.

Best Regards,

Tibaut Houzanme
-
Mobile: +1-317-332-3296
email: houzanme@gmail.com

   - www.linkedin.com/in/houzanme/
