### ISSUE TITLE
Cannot locate bagger.bat

### ISSUE THREAD

**Issue by jzarrillo** [LibraryOfCongress/bagger#31]
I have a feeling I'm making a foolish error, but I just downloaded the zip and cannot locate bagger.bat. The readme tells me to locate the directory bagger-2.1.3. I cannot find that either. And I missing something obvious?

**Comment by johnscancella** [comment]
which version did you download?
When you unzip bagger, the file structure should be something like:
```
bagger-<VERSION>
|
-- bin
    |
       bagger.bat
```
Where <VERSION> is the version you downloaded.

**Comment by jzarrillo** [comment]
I had downloaded the package of files from:
https://github.com/LibraryOfCongress/bagger

I have since downloaded the update you just posted at:
https://github.com/LibraryOfCongress/bagger/releases which is clearly what
I should have done in the first place!

I'm good to go now, thanks.
