### ISSUE TITLE
Character encoding issue while using a French version of WIndows 7

### ISSUE THREAD

**Issue by telliers** [LibraryOfCongress/bagger#33]
In the Bagger interface, when using a French version of Windows 7, there is an issue with character encoding when displaying default OS labels for some menus : 

![image](https://cloud.githubusercontent.com/assets/18740213/14920878/5c60096a-0dfd-11e6-939f-cb218ea8364d.png)

This was working well in Bagger 2.3 version.

**Comment by johnscancella** [comment]
This should be in the next release (2.7)
