### ISSUE TITLE
Problems with vertical scrollbar of Payload and Tag Files section

### ISSUE THREAD

**Issue by telliers** [LibraryOfCongress/bagger#34]
In Windows 7, there seems to be a problem with the vertical scrolling of the "Payload" and "Tag Files" section. 
For the Payload, while the scrollbar is visible, it doesn't detect the panel's new dimensions when adding multiple files.
For the Tag Files, it works partially, as the new dimensions are not correctly sets.
Those problems were also in version 2.3.
Here's some snapshots.

![image](https://cloud.githubusercontent.com/assets/18740213/14921367/f3bc20b2-0dff-11e6-92e4-0fc707e26e98.png)

![image](https://cloud.githubusercontent.com/assets/18740213/14921521/a881e252-0e00-11e6-9dc3-365deaad198e.png)

**Comment by telliers** [comment]
In the 2.3 version, I did the following modification in the gov.loc.repository.bagger.ui.BagTree class : 

Removed the line code `setPreferredSize(getTreeSize());`

It fixed the problem, but I don't know if it will also works well in other OS.

**Comment by johnscancella** [comment]
will be in version 2.6
