### ISSUE TITLE
Serialize to tarball?

### ISSUE THREAD

**Issue by bdwheele** [LibraryOfCongress/bagger#37]
We are going to start creating bags with a lot of A/V content that will not compress well and will be rather large (50G+).  Is it possible to add an option to serialize the bag to a tarball in addition to zip and directory?  Right now we're doing it as two steps.

**Comment by johnscancella** [comment]
In order to add this feature, a lot of work would have to be done on bagit-java (https://github.com/LibraryOfCongress/bagit-java) which is currently undergoing major changes. Thus it will not be done in time for you to use for you upcoming A/V project.

**Comment by bdwheele** [comment]
Thanks for the heads up.  I saw a bunch of commented-out code
      related to tarballs and was hopeful that it was an easy add.
    
    
    
    On 12/06/2016 04:46 PM, John Scancella
      wrote:
    
    
      
      In order to add this feature, a lot of work would have to be
        done on bagit-java (https://github.com/LibraryOfCongress/bagit-java)
        which is currently undergoing major changes. Thus it will not be
        done in time for you to use for you upcoming A/V project.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
          
          
        
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/LibraryOfCongress/bagger","title":"LibraryOfCongress/bagger","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/LibraryOfCongress/bagger"}},"updates":{"snippets":[{"icon":"PERSON","message":"@johnscancella in #37: In order to add this feature, a lot of work would have to be done on bagit-java (https://github.com/LibraryOfCongress/bagit-java) which is currently undergoing major changes. Thus it will not be done in time for you to use for you upcoming A/V project."}],"action":{"name":"View Issue","url":"https://github.com/LibraryOfCongress/bagger/issues/37#issuecomment-265282796"}}}

**Comment by johnscancella** [comment]
No, there are a couple of problems with tar which is why it was removed. You can see the discussion about it [here on bagit-java issue 22](https://github.com/LibraryOfCongress/bagit-java/issues/22)
