### ISSUE TITLE
Create bag in place with directory with dot in the directory name: Two bags are created

### ISSUE THREAD

**Issue by Jan321** [LibraryOfCongress/bagger#43]
Bagger 2.7.5, Win 7 (64 bit)

When I create a bag in place (using a profile) with a directory that contains a dot (.) in the directory name, then two bags are created: One bag with the original directory name, but with no specific profile data in the bag-info.txt AND a second bag without the dot and every character after the dot in the name but with the correct profile data in the bag-info.txt.
For example: The directory Test.Data is resulting in the bags Test.Data and Test

Regards,
Jan

**Comment by johnscancella** [comment]
Thanks Jan for submitting this bug. I think I have fixed it, please try https://github.com/LibraryOfCongress/bagger/releases/tag/v2.7.6 to confirm it fixes your problem.

**Comment by Jan321** [comment]
Yes, I can confirm that. Thanks John for the quick fix.
