### ISSUE TITLE
Difference in validation status of bag using Python and Java versions

### ISSUE THREAD

**Issue by johnscancella** [LibraryOfCongress/bagger#50]
from user https://github.com/jamiepb

I've discovered a discrepancy between the Java version and the Python version when validating a bag with an extra file. I have a bag that acquired a thumbs.db file when someone opened it. I ran a tool that is built on bagit-python (current pip install version, 1.6.2) that did not validate the bag, noting that the expected file count and bag size did not match. I then investigated and saw the thumbs.db file that had appeared after bagging. However, I then ran Bagger 2.7.6 and the bag validated.

Software and OS:

BagIt Python 1.6.2 and Bagger 2.7.6
Windows 7 Enterprise
Given

A bag with a thumbs.db file in it that is not on the manifest
When

I run a Python tool that calls bagit py 1.6.2
Then

The bag does not validate
BUT:

Given

A bag with a thumbs.db file in it that is not on the manifest
When

I open the bag in Bagger 2.7.6 and validate
Then

The validation is successful
Thank you for looking into it.

**Comment by johnscancella** [comment]
@jamiepb can you attach a sample bag that has this problem? I don't have a windows XP handy to readily create a thumbs.db file

**Comment by jamiepb** [comment]
Hello,

I zipped up a copy of the bag that has this problem, but it’s too large to attach. And strangely I can’t reproduce the problem – I tried making a new bag and opening the images within it to create a thumbs.db file, and that bag did not validate. So I have no idea what’s going on with the original bag in question.

Jamie

**Comment by johnscancella** [comment]
If you are able to create a smaller sample bag that reproduces the error I will take a look, otherwise I can't troubleshoot this.

**Comment by johnscancella** [comment]
closing from lack of response
