### ISSUE TITLE
Uncaught Exception Handler

### ISSUE THREAD

**Issue by jamiepb** [LibraryOfCongress/bagger#51]
Hello,

I am running Bagger 2.7.7 on Windows 7 Enterprise. On a particular bag receive the error "Exception: Java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Thread-4" The bag validates in the command-line, but not in Bagger. I've attached the log from opening the bag to trying to validate. 

Thank you,

Jamie

[BaggerUncaughtExceptionLog.txt](https://github.com/LibraryOfCongress/bagger/files/1775972/BaggerUncaughtExceptionLog.txt)

**Comment by johnscancella** [comment]
Hi Jamie,

How large is this Bag? I think the `NoClassDefFoundError ` is a red herring because I see in the log there is `java.lang.OutOfMemoryError: Java heap space` which means that Bagger ran out of memory.
Is this bag on local disk, on a external drive, or somewhere else?

**Comment by jamiepb** [comment]
Hi John,

The bag is 695 GB (308284 files), and it is on an external drive.

Jamie

JAMIE PATRICK-BURNS
Digital Archivist
State Archives of North Carolina

215 N Blount St MSC 4615 Raleigh, NC 27699
919 807 7355 office

[cid:image002.png@01D3B21F.C1077CA0]

Email correspondence to and from this address is subject to the North Carolina
Public Records Law and may be disclosed to third parties.

Facebook<http://www.facebook.com/NorthCarolinaCulture>  Twitter<http://www.twitter.com/ncculture>  Instagram<http://www.instagram.com/ncculture>  YouTube<http://www.youtube.com/ncculture>

**Comment by johnscancella** [comment]
[bagger.bat.txt](https://github.com/LibraryOfCongress/bagger/files/1776388/bagger.bat.txt)
rename this to bagger.bat and try running it again. This startup script allocates 3GB worth of memory for Bagger. 

It should be noted that we don't really support external drives due to the added complexity and IO errors that can occur.

**Comment by jamiepb** [comment]
Hi John,

Is there anywhere in particular I need to run this file from? I tried it from my desktop and get an error that says
“Error occurred during initialization of VM
Could not reserve enough space for 3145728KB object heap
Press any key to continue . . .”
But I’m wondering if that’s an issue with my computer more than anything else.

Thanks for your help.

JAMIE PATRICK-BURNS
Digital Archivist
State Archives of North Carolina

215 N Blount St MSC 4615 Raleigh, NC 27699
919 807 7355 office

[cid:image002.png@01D3B52B.9A66DCD0]

Email correspondence to and from this address is subject to the North Carolina
Public Records Law and may be disclosed to third parties.

Facebook<http://www.facebook.com/NorthCarolinaCulture>  Twitter<http://www.twitter.com/ncculture>  Instagram<http://www.instagram.com/ncculture>  YouTube<http://www.youtube.com/ncculture>

**Comment by johnscancella** [comment]
You want to put that file in the same location as the other bagger.bat file. But the error you are seeing is that it can't reserve the 3 GB of ram. Not being at your computer I can't 100% confirm, but it sounds like your computer needs more ram in order to verify the bag using bagger.

**Comment by jamiepb** [comment]
Hello,

I am running into another uncaught exception error with another large bag, and I wonder if it is the same problem. I've attached the log file. The bag is 101 GB with 94699 files. Thank you for your help.
[Bagger_error_log_04032018.txt](https://github.com/LibraryOfCongress/bagger/files/1871693/Bagger_error_log_04032018.txt)

**Comment by johnscancella** [comment]
@jamiepb you will notice it says in the log `java.lang.OutOfMemoryError: Java heap space`. The heap space is what java uses to do work. To put it simply you haven't given Bagger enough ram. From my earlier comments it seems that your computer simply doesn't have the ram needed to run Bagger for that large of a bag. I would recommend using https://github.com/LibraryOfCongress/bagit-python command line tool to validate it instead.
