### ISSUE TITLE
reopening a bag changes the order of key:value pairs defined in the json profile

### ISSUE THREAD

**Issue by 1jupp** [LibraryOfCongress/bagger#60]
Version: Bagger 2.8.1
OS: Windows 7
Java: jre-10.0.2 windows-x64 

Steps performed:

* create a new ordered -profile.json Profile save it in working directory
* start bagger
* select newly created profile 
* create new bag
* key:value pairs for Bag-Info are displayed in the GUI in correct order according to the -profile.json file 
* add some content
* click "save as.." button
* type in filepath
* click save
* Bag is saved
* key/value pairs are written to bag-info.txt in correct order according to the -profile.json file, profile name is included
* close bagger
* start bagger
* open saved bag
Expected outcome: key:value pairs for Bag-Info are displayed in the GUI in correct order according to the -profile.json file and the order in bag-info.txt
Problem: key:value pairs for Bag-Info are not displayed in the GUI in correct order according to the -profile.json file, but are being reordered by the application

I have read the thread on "Change fields (in Json profile, display screen and Bag-info) from set to ordered list" as well as the closed issue: "Bagger info panel unordered after saving" but I am ot sure if the problem has been solved and there is something wrong with my profile.

Thanks for any advice

J.Schminder

**Comment by jscancella** [comment]
Hi Schminder,

I suspect you are either running into the issue in #30 "Bagger info panel unordered after saving" if you have told the profile that the key:value must be ordered, or that you are just seeing the typical Bagger behavior of not displaying the key:value pairs in order. As long as there are no errors when it is trying to load or use a profile then you have done nothing wrong. Unfortunately I doubt the Library of Congress will fix this issue as Bagger is not under active development.

**Comment by 1jupp** [comment]
Yep, it is the Issue in #30. IIt does not do any harm, since the bag-info.txt is created correctly and the validation works etc. It is just a bit confusing. What a pity, that Bagger is not under active development. Do you know if that will change?

**Comment by jscancella** [comment]
Disclaimer: this is my own opinion and I do not work for the library of congress
From my experience there is little hope that the library of congress will put this in active development again.
