### ISSUE TITLE
Problem with JSON metadata profile

### ISSUE THREAD

**Issue by jamiepb** [LibraryOfCongress/bagger#68]
Hello,

I am trying to create a new metadata profile that I will request to be included in the Bagger code when it's finished. However I'm having trouble with the display of one of the fields and I can't figure out why. I've tried validating the json in an online validator and it seems valid, I've checked the spacing in the code, I tried making the default value and value options shorter, and I can't figure out why a drop down with values list is not displaying for a particular field. I have attached the JSON file and a screenshot of what I see, and details are listed below. Thank you.

Version: Bagger 2.8.1
OS: Windows 10

I saved the attached text file as a json file in my C:\Users\<username>\bagger folder alongside the other metadata profiles, and I was able to start Bagger and open up the profile and see how it looked. I expected the field "receivingInstitution" to have the default value of "State Archives of North Carolina, Division of North Carolina Department of Natural and Cultural Resources (Raleigh)" and to have a drop down menu of the other options, however I only see the default value in the field with no option of selecting another one. 
![bagger_json_problem](https://user-images.githubusercontent.com/34773710/107829574-0a29e700-6d58-11eb-98c3-94c2cde98c76.PNG)
[SANC-sc-profile.txt](https://github.com/LibraryOfCongress/bagger/files/5974564/SANC-sc-profile.txt)

**Comment by jscancella** [comment]
I used to work on this back when I worked at the LoC. Since I have left, I don't think anyone works on this anymore.

I looked into your problem and it looks like the max length a default list value can have is 30 characters long. Not really sure why this is, but it probably is something to do with spring rich client. Unfortunately the last release of it was back in 2009, and isn't supported anymore so I doubt it will ever be fixed.

**Comment by jamiepb** [comment]
Hi John,

I'm sorry to bother you with a Bagger question, but do you know who, if anyone, is working on Bagger anymore? I submitted a pull request for another metadata profile and received no response. I tried emailing some people I found through GitHub that work at LoC but never heard back. Any leads are much appreciated! Best,

Jamie


Jamie Patrick-Burns

Digital Archivist

State Archives of North Carolina

215 N Blount St MSC 4615 Raleigh, NC 27699

919 814 6905 office



 Know your 3 Ws!

WEAR - Wear a cloth mask over your nose and mouth.

WAIT - Wait 6 feet apart. Avoid close contact.

WASH - Wash your hands or use hand sanitizer.

 #StayStrongNC



¡Recuerda las 3 Ms!

MASCARILLA - Usar una mascarilla de tela cubriendo nariz y boca.

MANTENER - 6 pies (2 metros) de distancia. Evitar estar cerca de los demás.

MANOS - Lavarte las manos con frecuencia o usar desinfectante para manos.

#MantenteFuerteNC



Email correspondence to and from this address is subject to the North Carolina

Public Records Law and may be disclosed to third parties.



Facebook<http://www.facebook.com/NorthCarolinaCulture>  Twitter<http://www.twitter.com/ncculture>  Instagram<http://www.instagram.com/ncculture>  YouTube<http://www.youtube.com/ncculture>



________________________________
From: John Scancella ***@***.***>
Sent: Friday, February 12, 2021 7:29 PM
To: LibraryOfCongress/bagger ***@***.***>
Cc: Patrick-Burns, Jamie A ***@***.***>; Author ***@***.***>
Subject: [External] Re: [LibraryOfCongress/bagger] Problem with JSON metadata profile (#68)

CAUTION: External email. Do not click links or open attachments unless you verify. Send all suspicious email as an attachment to Report ***@***.***>


I used to work on this back when I worked at the LoC. Since I have left, I don't think anyone works on this anymore.

I looked into your problem and it looks like the max length a default list value can have is 30 characters long. Not really sure why this is, but it probably is something to do with spring rich client. Unfortunately the last release of it was back in 2009, and isn't supported anymore so I doubt it will ever be fixed.

**Comment by jscancella** [comment]
Jamie,

I am afraid I don't. The people that would be most likely are the ones you see in https://github.com/orgs/LibraryOfCongress/people. I would try reaching out using https://ask.loc.gov/comments-feedback/ as that way you might get someone from the technical department. Sorry I can't be of more help.

**Comment by jamiepb** [comment]
I hadn't thought of using the feedback form. Thank you very much for the suggestion.

Jamie


Jamie Patrick-Burns

Digital Archivist

State Archives of North Carolina

215 N Blount St MSC 4615 Raleigh, NC 27699

919 814 6905 office



 Know your 3 Ws!

WEAR - Wear a cloth mask over your nose and mouth.

WAIT - Wait 6 feet apart. Avoid close contact.

WASH - Wash your hands or use hand sanitizer.

 #StayStrongNC



¡Recuerda las 3 Ms!

MASCARILLA - Usar una mascarilla de tela cubriendo nariz y boca.

MANTENER - 6 pies (2 metros) de distancia. Evitar estar cerca de los demás.

MANOS - Lavarte las manos con frecuencia o usar desinfectante para manos.

#MantenteFuerteNC



Email correspondence to and from this address is subject to the North Carolina

Public Records Law and may be disclosed to third parties.



Facebook<http://www.facebook.com/NorthCarolinaCulture>  Twitter<http://www.twitter.com/ncculture>  Instagram<http://www.instagram.com/ncculture>  YouTube<http://www.youtube.com/ncculture>



________________________________
From: John Scancella ***@***.***>
Sent: Tuesday, June 22, 2021 7:58 AM
To: LibraryOfCongress/bagger ***@***.***>
Cc: Patrick-Burns, Jamie A ***@***.***>; State change ***@***.***>
Subject: [External] Re: [LibraryOfCongress/bagger] Problem with JSON metadata profile (#68)

CAUTION: External email. Do not click links or open attachments unless you verify. Send all suspicious email as an attachment to Report ***@***.***>


Jamie,

I am afraid I don't. The people that would be most likely are the ones you see in https://github.com/orgs/LibraryOfCongress/people<https://urldefense.com/v3/__https://github.com/orgs/LibraryOfCongress/people__;!!HYmSToo!OI13hnB86K9dnnatI2XxdNcH1NOtITpCGx2DaMsnz4haskh0T99QRtoZXwnLA_F6NKAUFG7Zhw$>. I would try reaching out using https://ask.loc.gov/comments-feedback/<https://urldefense.com/v3/__https://ask.loc.gov/comments-feedback/__;!!HYmSToo!OI13hnB86K9dnnatI2XxdNcH1NOtITpCGx2DaMsnz4haskh0T99QRtoZXwnLA_F6NKDFzALgQQ$> as that way you might get someone from the technical department. Sorry I can't be of more help.
