### ISSUE TITLE
bagger seems unresponsive after saving bag

### ISSUE THREAD

**Issue by andrewjcook** [LibraryOfCongress/bagger#8]
Hi:

Demonstrated this issue in person with John Scancella on 20150817. 

The issue is that after you use the option "Create New Bag" (which works fine-first screenshot), when you click on the "Validate" icon (second screenshot), it doesn't appear to do anything. (Actually, it appears the other four icons to the right of the Validate icon don't get a response either, if I'm not mistaken.)

The way I discovered to resolve this is to select the Terminal window--which brings it in front of the Bagger GUI window (third screenshot) and the window that the validation is successful appears.

Thank you.

Andrew Cook
acook@loc.gov
Library of Congress

![screen shot 2015-08-17 at 10 28 41 am](https://cloud.githubusercontent.com/assets/13834450/9307275/9f09b3de-44cb-11e5-8823-318d8fe5a6ba.png)
![screen shot 2015-08-17 at 10 29 24 am](https://cloud.githubusercontent.com/assets/13834450/9307277/9f133f1c-44cb-11e5-9942-67f070963b26.png)
![screen shot 2015-08-17 at 10 30 21 am](https://cloud.githubusercontent.com/assets/13834450/9307276/9f0cf21a-44cb-11e5-9ce1-b17a748ece1c.png)

**Comment by johnscancella** [comment]
turns out this was due to using the wrong dependencies from before. That happened because of #6 when the repo for spring rich client was added, but their artifacts weren't the actual 1.1.0 release from source forge. Once I updated gradle to use the actual source forge release it seems to have fixed the problem.

**Comment by johnscancella** [comment]
This will be in release version 2.4
