### ISSUE TITLE
suggested feature enhancement to future version of Bagger

### ISSUE THREAD

**Issue by andrewjcook** [LibraryOfCongress/bagger#9]
Hi:

Writing to suggest adding a vertical scroll bar for scrolling in the Payload section (due to some of the files under Payload not being viewable when the number of files gets long).

![screen shot 2015-08-17 at 3 28 10 pm](https://cloud.githubusercontent.com/assets/13834450/9314298/0be4712c-44f6-11e5-8f72-578c736979e0.png)

**Comment by johnscancella** [comment]
should be in next release (2.5)
